name = "storemaster-worker"

main = "worker.js"

compatibility_date = "2026-09-03"

account_id = "06c26ba021336c89415210cb3338b9b4"


[vars]

GITHUB_OWNER = "one-wil"


[[kv_namespaces]]

binding = "LICENSES"

id = "40968148c6684be5b504574d537bdaf6"
